language: objective-c
osx_image: xcode8.2
env:
  global:
  - IOS_SDK=iphonesimulator10.2
  - SCHEME=CustomLoader
  - WORKSPACE=CustomLoader.xcworkspace
  matrix:
    - DESTINATION="OS=10.1,name=iPhone 7" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPhone 5s" SDK="$IOS_SDK" POD_LINT="YES"
script:
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi